quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
]

quotes/quoteapp/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=25, null=False, unique=True)

    def __str__(self):
        return f'{self.name}'
    
class Quote(models.Model):
    author = models.ForeignKey('Author', on_delete=models.CASCADE,)
    text = models.CharField(max_length=2000, null=False, unique=True)
    tags = models.ManyToManyField(Tag)
    
    def __str__(self):
        return f'{self.text}'

class Author(models.Model):
    fullname = models.CharField(max_length=25, null=False, unique=True)
    born_date = models.CharField(max_length=25, null=False)
    born_location = models.CharField(max_length=25, null=False)
    description = models.CharField(max_length=5000, null=False, unique=True)

    def __str__(self):
        return f'{self.fullname}'

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class AuthorForm(ModelForm):
    
    fullname = CharField(min_length=1, max_length=25, required=True, widget=TextInput())
    born_date = CharField(min_length=10, max_length=25, required=True, widget=TextInput())
    born_location = CharField(min_length=5, max_length=25, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=5000, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(ModelForm):

    text = CharField(min_length=10, max_length=5000, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['text']
        exclude = ['author', 'tags']

quotes/quoteapp/views.py
from django.shortcuts import render, redirect
from quoteapp.forms import TagForm, AuthorForm, QuoteForm
from quoteapp.models import Tag, Author


# Create your views here.
def main(request):
    return render(request, 'quoteapp/index.html')

def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})

def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})
        
    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})

def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            
            choice_authors = Author.objects.filter(fullname__in=request.POST.getlist('authors'))
            for author in choice_authors.iterator():
                new_quote.author.add(author)

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"authors": authors, "tags": tags, 'form': form})

    return render(request, 'quoteapp/quote.html', {"authors": authors, "tags": tags, 'form': QuoteForm()})

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>Quotes to Scrape</h1>
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.text }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="authors" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}